# Generated by Django 4.0.3 on 2022-03-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcclassicsapi', '0002_remove_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
