# Generated by Django 4.0.3 on 2022-03-16 23:59

from django.db import migrations, models
import mcclassicsapi.models.gearhead
import mcclassicsapi.models.projects


class Migration(migrations.Migration):

    dependencies = [
        ('mcclassicsapi', '0003_alter_gearhead_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearhead',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=mcclassicsapi.models.gearhead.upload_path2),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mcclassicsapi.models.projects.upload_path),
        ),
    ]
