# Generated by Django 4.0.3 on 2022-03-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcclassicsapi', '0003_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearhead',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='profilepics'),
        ),
    ]
