# Generated by Django 4.0.3 on 2022-03-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcclassicsapi', '0004_alter_gearhead_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearhead',
            name='profile_img',
        ),
    ]
